### ISSUE TITLE
TypeError: Cannot read property 'source' of undefined

### ISSUE THREAD

**Issue by AlexDel** [webpack-contrib/worker-loader#134]
[ webpack 4.1.0, worker-loader 1.1.1]

**myService.js**
`import Worker from './summary.worker';`

**webpack.config.js**
`{
     test: /\.worker\.js$/,
     use: { loader: 'worker-loader' }
  }`

On trying to build console emits this:

```
C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\worker-loader\dist\index.js:121
      worker.factory = (0, _workers2.default)(worker.file, compilation.assets[worker.file].source(), options);
                                                                                              ^
TypeError: Cannot read property 'source' of undefined
    at C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\worker-loader\dist\index.js:121:92
    at compile (C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\webpack\lib\Compiler.js:222:11)
    at hooks.afterCompile.callAsync.err (C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\webpack\lib\Compiler.js:470:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\webpack\node_modules\tapable\lib\Hook.js:35:21)
    at compilation.seal.err (C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\webpack\lib\Compiler.js:467:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\webpack\node_modules\tapable\lib\Hook.js:35:21)
    at hooks.optimizeAssets.callAsync.err (C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\webpack\lib\Compilation.js:957:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\webpack\node_modules\tapable\lib\Hook.js:35:21)
    at hooks.optimizeChunkAssets.callAsync.err (C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\webpack\lib\Compilation.js:948:32)
    at _err0 (eval at create (C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:11:1)
    at C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\webpack\node_modules\uglifyjs-webpack-plugin\dist\index.js:262:11
    at _class.runTasks (C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\webpack\node_modules\uglifyjs-webpack-plugin\dist\uglify\index.js:63:9)
    at UglifyJsPlugin.optimizeFn (C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\webpack\node_modules\uglifyjs-webpack-plugin\dist\index.js:182:16)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\webpack\node_modules\tapable\lib\Hook.js:35:21)
    at hooks.additionalAssets.callAsync.err (C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\webpack\lib\Compilation.js:943:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\webpack\node_modules\tapable\lib\Hook.js:35:21)
    at hooks.optimizeTree.callAsync.err (C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\webpack\lib\Compilation.js:939:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\webpack\node_modules\tapable\lib\Hook.js:35:21)
    at Compilation.seal (C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\webpack\lib\Compilation.js:881:27)
    at hooks.make.callAsync.err (C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\webpack\lib\Compiler.js:464:17)
    at _err0 (eval at create (C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:24:12), <anonymous>:11:1)
    at _addModuleChain (C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\webpack\lib\Compilation.js:749:12)
    at processModuleDependencies.err (C:\Users\verba\gg\incubator-ignite\modules\web-console\frontend\node_modules\webpack\lib\Compilation.js:688:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by AlexDel** [comment]
It appeard that some some part of code contained inline requiring with loader, like this:

`import Worker from 'worker-loader!./pack.worker'; `

After removing 'worker-loader!' bundle seems to be built.

**Comment by akuznetsov-gridgain** [comment]
+1 I also need this fix.

**Comment by huy-nguyen** [comment]
@AlexDel I got the same error with the same call stack but didn't use `eslint-loader`. I'm on `webpack` 4.2.0 and `worker-loader` 1.1.1.

**Comment by Manc** [comment]
If anybody comes across this in the future – this is what caused the problem for me and a solution.

I set the `name` option to `w.[contenthash:8].js`, which caused the error from above, but only when I ran Webpack in *development* mode (*production* mode was fine).

My solution:

	use: [
		{
			loader: 'worker-loader',
			name: isDev ? 'w.[hash].js' : 'w.[contenthash:8].js',
		},
	]

Or simply use `[hash]` in both cases, of course.

**Comment by eranimo** [comment]
Also getting this error, rather randomly. Also on Webpack 4, no eslint-loader.

**Comment by futurechallenger** [comment]
When I try to use the `inline` mode, I met this problem too. Here's how I solved this problem:
```json
{
          // loader: 'worker-loader',
          // options: {
          //   inline: true, 
          //   fallback: false,
          // }
          test: /\.worker\.js$/,
          use: { 
            loader: 'worker-loader',
            options: {
              inline: true, 
              fallback: false,
            }
          },
        },
```
