### ISSUE TITLE
CORS issue with Chrome Extension + worker-loader

### ISSUE THREAD

**Issue by dwalintukan** [webpack-contrib/worker-loader#158]
Node: 9.3.0
OS: Mac OS High Sierra 10.13.6

Long story short, I have a Chrome extension that has some cryptography intense logic that I need to offset to a Worker. The background script is trying to initialize the Worker but I am getting a `CORS error`. I have follow the instructions, but to on avail.

I have also tried to use the `publicPath` option, but when I try to build with webpack it freezes and doesn't build.

**Error**
```
Uncaught (in promise) DOMException: Failed to construct 'Worker': Script at 'chrome-extension://extension_id__/df21b72af8098b9d2e68.worker.js' cannot be accessed from origin 'chrome-extension://dinkholgplhfbmnnjaahkjlbponanlmc'.
    at new module.exports (webpack-internal:///./src/background/workers/passwordHash.worker.js:2:10)
    at CryptoController.derivePasswordHash (webpack-internal:///./src/background/controllers/cryptoController.ts:45:28)
    at AccountController.login (webpack-internal:///./src/background/controllers/accountController.ts:49:40)
    at AccountController.handleMessage (webpack-internal:///./src/background/controllers/accountController.ts:284:26)
    at EventImpl.dispatchToListener (extensions::event_bindings:403:22)
    at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26)
    at EventImpl.dispatch_ (extensions::event_bindings:387:35)
    at EventImpl.dispatch (extensions::event_bindings:409:17)
    at Event.publicClassPrototype.(anonymous function) [as dispatch] (extensions::utils:138:26)
    at messageListener (extensions::messaging:240:29)
```

**worker.js**
```
import scrypt from 'scryptsy';

import { TARGET_NAME } from '../../constants';
import Config from '../../config';

const derivePasswordHash = (appSalt, password) => {
  const saltBuffer = Buffer.from(appSalt);
  const { N, r, p } = Config.SCRYPT_PARAMS.PASSWORD;
  const derivedKey = scrypt(password, saltBuffer, N, r, p, 64);

  const passwordHash = derivedKey.toString('hex');
  postMessage({
    passwordHash,
  }, TARGET_NAME.PASSWORD_HASH_WORKER);
};

self.addEventListener('message', (event) => {
  if (event.data.target === TARGET_NAME.PASSWORD_HASH_WORKER) {
    const { appSalt, password } = event.data;
    derivePasswordHash(appSalt, password);
  }
}, false);
```

**background script**
```
import Worker from '../workers/passwordHash.worker.js';

public derivePasswordHash = async (password: string): Promise<any> => {
    const worker = new Worker();
    worker.postMessage({
      target: TARGET_NAME.PASSWORD_HASH_WORKER,
      appSalt: this.appSalt,
      password,
    });
    worker.onmessage = (event) => {
      console.log(event);
    };
}
```

**webpack config**
```
module: {
    rules: [
      {
        oneOf: [
          // others omitted
          {
            test: /\.worker\.js$/,
            use: { loader: 'worker-loader' }
          },
        ],
      }
    ]
  },
```

**Comment by evilebottnawi** [comment]
Yes, there are a lot of limitations for extensions, this is exactly what it is, if want to use known domain you can use `permissions`, more information https://developer.chrome.com/extensions/xhr, otherwise please use `{ inline: true, fallback: false }`. Perhaps at the moment there are new features that allow to do this, but I can't find documentation about them. If you known how it can be done without `inline: true` feel free to feedback or send a PR to docs, sorry for delay
