### ISSUE TITLE
Unable to work with wasm-loader and typescript in react project

### ISSUE THREAD

**Issue by aeroxy** [webpack-contrib/worker-loader#237]
I've tried:

```
// Worker.ts
// @ts-ignore
// eslint-disable-next-line no-restricted-globals
const ctx: Worker = self as any;

// Post data to parent thread
// ctx.postMessage({ foo: "foo" });

// Respond to message from parent thread
ctx.addEventListener('message', async ({ data }) => {
  const {
    href,
    width,
    height
  } = data;
  const { qrcode } = await import('uranus-qrcode');
  const qr = qrcode(href, width, height);
  ctx.postMessage({ href, qr });
});
```

in which `uranus-qrcode` is a Rust-Wasm module I created. I use wasm-loader to load it, and it works when I load it into the main thread, but when I tried it with worker-loader it says:

```
Uncaught (in promise) TypeError: Cannot read property './modules/uranus_qrcode/uranus_qrcode_bg.wasm' of undefined
    at Object../modules/uranus_qrcode/uranus_qrcode_bg.wasm (http://localhost:3334/0.34621aa454b5fe6ea3b4.worker.js:145:40)
    at __webpack_require__ (http://localhost:3334/34621aa454b5fe6ea3b4.worker.js:34:30)
    at Module../modules/uranus_qrcode/uranus_qrcode.js (http://localhost:3334/0.34621aa454b5fe6ea3b4.worker.js:12:80)
    at __webpack_require__ (http://localhost:3334/34621aa454b5fe6ea3b4.worker.js:34:30)
    at async http://localhost:3334/34621aa454b5fe6ea3b4.worker.js:139:7
```

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/worker-loader/issues/251
