### ISSUE TITLE
TypeError Cannot assign to read only property 'cache' of object

### ISSUE THREAD

**Issue by Matrixbirds** [webpack-contrib/worker-loader#242]
```bash
[webpack-cli] Module build failed (from ./node_modules/worker-loader/dist/cjs.js):
TypeError: Cannot assign to read only property 'cache' of object '#<Compilation>'
    at worker.compilation (/someone/Project/workspace/build-lab/next-education-web/node_modules/worker-loader/dist/index.js:104:25)
    at Hook.eval [as call] (eval at create (/someone/Project/workspace/build-lab/next-education-web/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:91:1)
    at Hook.CALL_DELEGATE [as _call] (/someone/Project/workspace/build-lab/next-education-web/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/someone/Project/workspace/build-lab/next-education-web/node_modules/webpack/lib/Compiler.js:867:26)
    at /someone/Project/workspace/build-lab/next-education-web/node_modules/webpack/lib/Compiler.js:907:29
    at Hook.eval [as callAsync] (eval at create (/someone/Project/workspace/build-lab/next-education-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:4:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/someone/Project/workspace/build-lab/next-education-web/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/someone/Project/workspace/build-lab/next-education-web/node_modules/webpack/lib/Compiler.js:902:28)
    at Compiler.runAsChild (/someone/Project/workspace/build-lab/next-education-web/node_modules/webpack/lib/Compiler.js:445:8)
    at Object.pitch (/someone/Project/workspace/build-lab/next-education-web/node_modules/worker-loader/dist/index.js:116:19)
```

Env:
```bash
nodejs v12.16.3
webpack-cli 1.0.0
webpack 5.0.0-beta.17
```

`webpack.config.js`
```js
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const {CleanWebpackPlugin} = require('clean-webpack-plugin');
const env = process.env.NODE_ENV
const mode = env === 'production' ? 'production': 'none'

module.exports = {
  mode,
  entry: {
    main: './src/main.tsx'
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
      'stream': 'stream-browserify'
    },
    extensions: ['.tsx', '.ts', '.js']
  },
  module: {
    rules: [
      {
        test: /\.(js|ts)x?$/,
        exclude: /node_modules/,
        include: /src/,
        use: [{
          loader: require.resolve("babel-loader"),
          options: {
            babelrc: true
          }
        }]
      },
      {
        test: /\.(css|scss)$/,
        use: [
          'style-loader',
          'css-loader',
          {
            loader: require.resolve('sass-loader'),
          }
        ]
      },
      {
        test: /\.(png|svg|jpg|jpeg|gif|ico)$/,
        exclude: /node_modules/,
        include: /src/,
        use: ['file-loader?name=[name].[ext]']
      },
      {
        test: /\.worker\.(js|ts)x?$/,
        use: [
          {
            loader: 'worker-loader',
            options: {
              inline: true,
              name: 'worker.[hash].js'
            },
          }
        ],
      }
    ]
  },
  devServer: {
    contentBase: './dist'
  },
  plugins: [
    new CleanWebpackPlugin(),
    new HtmlWebpackPlugin({
        template: 'public/index.html'
    })
  ], 
  output: {
    filename: '[name].bundle.js',
    path: path.resolve(__dirname, 'dist'),
  },
};

```

`.babelrc`
```json
{
  "presets": ["@babel/preset-react", "@babel/env", "@babel/typescript"],
  "plugins": [
    "@babel/proposal-class-properties",
    "@babel/proposal-object-rest-spread"
  ]
}
```

reproduce:
```
webpack --config webpack.config.js --dev
```

I was tried both dev and prod build option, but i don't find any thread to find what's going wrong. Can anyone give me some advice.

**Comment by dat23** [comment]
I'm getting the same error also.
Env:
```
nodejs: v12.18.0
webpack:  5.0.0-beta.17
webpack-cli: 3.3.11
worker-loader: 2.0.0
```

Webpack config:
```
var webpackOptions = {
	mode: 'production',
	devtool: 'source-map',
	cache: false,
	watch: false,
	entry: entries,
	output: {
		path: path.join(__dirname, '../static/dist'),
		filename: '[name].js',
		publicPath: '/dist/'
	},
	module: {
		rules: [
			{
				test: /\.jsx?$/,
				loader: 'babel-loader',
				include: [path.resolve(__dirname, '..', 'client'), /brucke-ui\/dist\/es/],
				options: {
					presets: [
						[
							'@babel/preset-env',
							{
								targets: {
									browsers: ['last 2 versions', 'safari >= 7']
								}
							}
						],
						'@babel/preset-react'
					],
					plugins: [
						'@babel/plugin-transform-react-jsx',
						// Stage 0
						'@babel/plugin-proposal-function-bind',

						// Stage 1
						'@babel/plugin-proposal-export-default-from',
						['@babel/plugin-proposal-optional-chaining', { loose: false }],

						// Stage 2
						['@babel/plugin-proposal-decorators', { legacy: true }],
						'@babel/plugin-proposal-export-namespace-from',
						'@babel/plugin-proposal-throw-expressions',

						// Stage 3
						'@babel/plugin-syntax-dynamic-import',
						'@babel/plugin-syntax-import-meta',
						['@babel/plugin-proposal-class-properties', { loose: true }]
					],
					cacheDirectory: true
				}
			},
			{
				test: /\.js$/,
				loader: 'eslint-loader',
				options: {
					fix: true
				},
				include: path.resolve(__dirname, '..', 'client')
			},
			{
				test: /\.css$/,
				use: ['style-loader', 'css-loader']
			},
			{
				test: /\.worker\.js$/,
				use: { loader: 'worker-loader' }
			},
			{
				test: /\.less$/,
				use: ['style-loader', 'css-loader', 'less-loader']
			},
			{
				test: /\.scss$/,
				use: [
					'style-loader',
					'css-loader',
					{
						loader: 'sass-loader',
						options: {
							includePaths: [path.resolve(__dirname, '..', 'node_modules')]
						}
					}
				]
			},
		]
	},
	resolve: {
		extensions: ['.js', '.json', '.jsx', '.css', '.scss'],
		alias: {
			react: path.resolve('./node_modules/react'),
			'react-dom': path.resolve('./node_modules/react-dom')
		}
	},
	plugins: [
		new CaseSensitivePathsPlugin(),
		new webpack.DefinePlugin({
			'process.env': {
				NODE_ENV: JSON.stringify('production')
			}
		})
	]
};

```

**Comment by evilebottnawi** [comment]
Fixed in the master, ETA is today/tomorrow

**Comment by reda-alaoui** [comment]
> Fixed in the master, ETA is today/tomorrow

No publication since. Could you publish please?

**Comment by evilebottnawi** [comment]
@reda-alaoui some additional problems, ETA is the end of week

**Comment by CXuesong** [comment]
@reda-alaoui Before actual publish, I think installing the package from git directly can help
```pwsh
yarn add --dev https://github.com/webpack-contrib/worker-loader.git#master
```

However, I'm blocked by the following runtime error when loading the web worker:
```
Uncaught Error: Module parse failed: Unexpected token (10:29)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.
```

Seem there is still bug with current commit that prevents applying registered loaders to the worker script.
