### ISSUE TITLE
does worker-loader work with webpack 5?

### ISSUE THREAD

**Issue by osheroff** [webpack-contrib/worker-loader#319]
- Operating System: OSX big sur
- Node Version: 15.11.0
- NPM Version: yarn 1.22.10
- webpack Version: 5.37.1
- worker-loader Version: 3.0.8

I'm attempting to use worker-loader 3.0.8 to strap in the web worker for the latest version of pdf.js.  Upgrading pdf.js has triggered a fairly massive upgrade of my entire build chain and I am on the uncomfortably modern edge of a lot of packages.  
I'm getting this stack trace:

### Actual Behavior

```
./vue-pdf/node_modules/worker-loader/dist/cjs.js!../vue-pdf/node_modules/pdfjs-dist/build/pdf.worker.js 39 bytes [not cacheable] [built] [code generated] [1 error]

ERROR in ../vue-pdf/node_modules/pdfjs-dist/build/pdf.worker.js (../vue-pdf/node_modules/worker-loader/dist/cjs.js!../vue-pdf/node_modules/pdfjs-dist/build/pdf.worker.js)
Module build failed (from ../vue-pdf/node_modules/worker-loader/dist/cjs.js):
TypeError: The 'compilation' argument must be an instance of Compilation
    at getCompilationHooks (/Users/ben/src/vue-pdf/node_modules/webpack/lib/javascript/JavascriptModulesPlugin.js:125:10)
    at /Users/ben/src/vue-pdf/node_modules/webpack/lib/javascript/ArrayPushCallbackChunkFormatPlugin.js:41:19
    at Hook.eval [as call] (eval at create (/Users/ben/src/mainstage/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/ben/src/mainstage/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/Users/ben/src/mainstage/node_modules/webpack/lib/Compiler.js:1030:30)
    at /Users/ben/src/mainstage/node_modules/webpack/lib/Compiler.js:1073:29
    at Hook.eval [as callAsync] (eval at create (/Users/ben/src/mainstage/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/ben/src/mainstage/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/Users/ben/src/mainstage/node_modules/webpack/lib/Compiler.js:1068:28)
    at Compiler.runAsChild (/Users/ben/src/mainstage/node_modules/webpack/lib/Compiler.js:520:8)
    at runAsChild (/Users/ben/src/vue-pdf/node_modules/worker-loader/dist/supportWebpack5.js:11:26)
    at Object.pitch (/Users/ben/src/vue-pdf/node_modules/worker-loader/dist/index.js:95:33)
 @ ./node_modules/vue-loader/lib/index.js??vue-loader-options!../vue-pdf/src/vuePdfNoSss.vue?vue&type=script&lang=js& 7:20-75
```

### Code

the code in question attempts to load up a worker from a node_modules.  I couldn't for the life of me figure out how I might do that with webpack 5's native worker-fu.

```
const PDFJSWorker = require('worker-loader!pdfjs-dist/build/pdf.worker.js');
```

Am I not supposed to be using worker-loader with webpack 5?  Is there a simpler way to do this?  thank you so much for your expertise.  I have none.

-osheroff

**Comment by osheroff** [comment]
nevermind, this was due to a bad yarn-link configuration; worker-loader was using its own version of webpack which was causing some confusion.

**Comment by gunn4r** [comment]
> nevermind, this was due to a bad yarn-link configuration; worker-loader was using its own version of webpack which was causing some confusion.

Running into this issue right now. What was the resolution?

**Comment by osheroff** [comment]
I found that there were two copies of webpack loaded (one worker-loaders's's `node_modules`).  There's a strict object equality check in `getCompilationHooks` (is this the object the copy of webpack something that I loaded?) that fails when this is the case.

I think you can also trigger this by running a global copy of webpack that conflicts with worker-loader's local copy.

**Comment by gunn4r** [comment]
Yeah looks like youre right. I forced the resolution of my version of WP, fixed it right up. 👍
