### ISSUE TITLE
TypeError: The 'compilation' argument must be an instance of Compilation

### ISSUE THREAD

**Issue by masx200** [webpack-contrib/worker-loader#334]
### Bug report
TypeError: The 'compilation' argument must be an instance of Compilation

### Expected Behavior
There should be no errors.
### Actual Behavior

```
ERROR in ./src/components/JSfuck-and-hieroglyphy-Decoder-and-ENCODER/worker-hieroglyphy.worker.js

Module build failed (from ./node_modules/worker-loader/dist/cjs.js):

TypeError: The 'compilation' argument must be an instance of Compilation

    at getCompilationHooks (D:\Documents\GitHub\masx200-github-io\node_modules\webpack\lib\javascript\JavascriptModulesPlugin.js:138:10)

    at D:\Documents\GitHub\masx200-github-io\node_modules\webpack\lib\javascript\ArrayPushCallbackChunkFormatPlugin.js:41:19

    at Hook.eval [as call] (eval at create (D:\Documents\GitHub\masx200-github-io\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)

    at Hook.CALL_DELEGATE [as _call] (D:\Documents\GitHub\masx200-github-io\node_modules\tapable\lib\Hook.js:14:14)

    at Compiler.newCompilation (D:\Documents\GitHub\masx200-github-io\node_modules\@masx200\webpack-react-vue-spa-awesome-config\node_modules\webpack\lib\Compiler.js:1043:30)

    at D:\Documents\GitHub\masx200-github-io\node_modules\@masx200\webpack-react-vue-spa-awesome-config\node_modules\webpack\lib\Compiler.js:1088:29

    at Hook.eval [as callAsync] (eval at create (D:\Documents\GitHub\masx200-github-io\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)

    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\Documents\GitHub\masx200-github-io\node_modules\tapable\lib\Hook.js:18:14)

    at Compiler.compile (D:\Documents\GitHub\masx200-github-io\node_modules\@masx200\webpack-react-vue-spa-awesome-config\node_modules\webpack\lib\Compiler.js:1083:28)

    at Compiler.runAsChild (D:\Documents\GitHub\masx200-github-io\node_modules\@masx200\webpack-react-vue-spa-awesome-config\node_modules\webpack\lib\Compiler.js:532:8)

    at runAsChild (D:\Documents\GitHub\masx200-github-io\node_modules\worker-loader\dist\supportWebpack5.js:11:26)

    at Object.pitch (D:\Documents\GitHub\masx200-github-io\node_modules\worker-loader\dist\index.js:95:33)

 @ ./src/components/JSfuck-and-hieroglyphy-Decoder-and-ENCODER/react-module-hieroglyphy.tsx 1:716-778 1:1963-1980

 @ ./src/router-react-路由列表.tsx 1:1039-1133

 @ ./src/home-react-index-render.tsx 1:107-145 1:676-680

 @ ./src/index.tsx
```

### How Do We Reproduce?
``` 
{
                test: /\.worker\.(js|ts)$/,
                loader: require.resolve("worker-loader"),
                options: {
                    inline: "no-fallback"
                }
            }
```
```
 webpack-cli "^4.8.0"
    webpack-dev-server "^4.1.0"
 webpack "5.47"
    worker-loader "^3.0.8"
```
```
webpack  'build'   '--config=D:\\Documents\\GitHub\\masx200-github-io\\webpack.config.js'  '--mode=production'
```

### Please paste the results of `npx webpack-cli info` here, and mention other relevant information
```

  System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
    Memory: 2.33 GB / 7.85 GB
  Binaries:
    Node: 16.8.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
    npm: 7.21.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (93.0.961.38)
    Internet Explorer: 11.0.19041.906
  Packages:
    clean-webpack-plugin: ^4.0.0-alpha.0 => 4.0.0-alpha.0
    html-webpack-plugin: ^5.3.1 => 5.3.2
    optimize-css-assets-webpack-plugin: ^6.0.0 => 6.0.1
    terser-webpack-plugin: ^5.1.2 => 5.1.4
    webpack: 5.47 => 5.47.1
    webpack-cli: ^4.8.0 => 4.8.0
    webpack-copyfiles-plugin: ^1.0.9 => 1.0.9
    webpack-dev-server: ^4.1.0 => 4.1.0
    webpack-inject-plugin: ^1.5.5 => 1.5.5
    webpack-replace-loader: ^1.3.0 => 1.3.0
    workbox-webpack-plugin: ^6.1.5 => 6.1.5
```

When webpack is 5.44.0, it works normally.

**Comment by alexander-akait** [comment]
You don't need this load for webpack v5, please read https://webpack.js.org/guides/web-workers/

**Comment by masx200** [comment]
I found out that this problem is caused by the existence of multiple different versions of webpack at the same time.
